## 로컬 테스트 + 로컬 DB
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/playlist
##    GIT 용
#    username:
#    password:
#    hikari:
#      maximum-pool-size:4
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#        use_sql_comments: true
#
#  config:
#    activate:
#      on-profile: local
